### ISSUE TITLE
Зачем этот проект?

### ISSUE THREAD

**Issue by re7gog** [CodeName33/TGAudioToText#1]
Чел, просто поставь Аюграм, там бесплатно расшифровка работает с локальным премиумом

**Comment by Radiquum** [comment]
как минимум в том, что это так же работает и с компьютерного клиента, а не только с мобильного, который нарушает правила телеграм.

**Comment by re7gog** [comment]
> как минимум в том, что это так же работает и с компьютерного клиента, а не только с мобильного, который нарушает правила телеграм.

Фурей не спрашивали
